delete share confirmation
IONOS-Productivity/nc-server pull request #27
Opened 2024-08-02 16:04 UTC by printminion-co

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-08-05 12:33 UTC, bromiesTM requested changes
We should try to make this upstreamable 
Also please make sure to add yourself to the license header and ensure the compilation works properly

2024-08-05 12:33 UTC, bromiesTM commented on apps/files_sharing/src/mixins/SharesMixin.js
> +				.setName(t('files_sharing', 'You are about to delete share'))
typo: 
```suggestion
				.setName(t('files_sharing', 'You are about to delete a share'))
```

2024-08-06 09:21 UTC, printminion-co commented
changed text in order to be similar to "delete files" confirmation dialog
![Selection_20240806-001](https://github.com/user-attachments/assets/a21145f6-c879-4e88-8872-2e9e2b992614)

2024-08-06 16:53 UTC, thlehmann-ionos approved these changes
Mostly OK for me, a couple of minor notes though.

- [x] Looks good to me (cancel does not delete, confirm deletes) :green_heart: 
- [x] Unit tests OK :heavy_check_mark:  
- [x] Linter OK :heavy_check_mark: 
- [x] Code style OK if one review note is addressed (semi-colon) :heavy_check_mark: 
- [x] Cypress tests don't seem to test or use this: OK   :heavy_check_mark: 

1. I'd like to see the semi-colon removed, the superfluous parens removed and the async/await vs. Promise mixture changed
2. I'm undecided on the action button type and leave it up to you since there's no clear guide (you may want to mention this when upstreaming this as a PR)

2024-08-07 14:16 UTC, merged