IONOS(feat): add ionos_processes custom app
IONOS-Productivity/nc-server pull request #48
Opened 2024-10-21 14:02 UTC by thlehmann-ionos

The app implements sending share create mails to our internal mail service.

2024-10-22 07:25 UTC, bromiesTM requested changes
The submodule commit is outdated and for example still features some mentions of nc_theming in the composer.json. We should update it to the latest version of the initial commit :))

2024-10-22 07:26 UTC, bromiesTM commented
Is this app supposed to be activated via occ or via our config scripts?

2024-10-25 07:36 UTC, printminion-co approved these changes
review ok

2024-10-28 10:56 UTC, printminion-co commented
upgraded to latest config a02c486a87b...7248412993c tl/dev/add-ionos-processes-app

2025-01-07 15:06 UTC, closed without merging